urls.py
from django.urls import path
from . import views

app_name = 'G865'
urlpatterns = [
            path('', views.index, name='G865'),
            path('l4video', views.l4_video, name='lesson-4-video'),
            path('test', views.test, name='test'),
            path('lesson5', views.lesson5, name='lesson5'),
            path('final/queue', views.final_queue, name="final-queue"),
            path('final/ec2', views.ec2, name='final-ec2'),
            path('final/queue/tasks', views.task_list, name='task-list'),
            path('final/queue/tasks/<str:task_id>', views.task_item, name='task-item'),
            path('final/video', views.final_video, name='final-video')
            ]

templates/G865/ec2.html
{% extends "G865/lesson-template.html" %}
{% load static %}

{% block title %}Geal's GEOG:865 EC2 Server Manager{% endblock %}
{% block page-title %}GEOG: 865 EC2 Server Manager{%endblock %}


{% block lesson-content %}
    <h2>Server Statuses</h2>
    <ul>
        {% for server, status in statuses.items %}
            <li>{{server}}: {{status}}</li>
        {% endfor %}
    </ul>

    <form method="POST">
        {% csrf_token %}
        <button type="Submit" name="Switch" value="On" class='site-button'>Turn Servers On</button>
        <button type="Submit" name="Switch" value="Off" class='site-button'>Turn Servers Off</button>
        <button type="Submit" formmethod="get" class='site-button'>Refresh Status</button>
    </form>
{% endblock %}

templates/G865/final-queue.html
{% extends "G865/lesson-template.html" %}
{% load static %}

{% block title %}Geal's GEOG:865 Queue Submitter{% endblock %}
{% block page-title %}GEOG: 865 Queue Task Submitter{%endblock %}


{% block lesson-content %}
    <div id="Disclaimer" style="color: red; background: black">
        The distributed EC2 instances used for this project have been shut down to save on running costs. If you would like to demo the capabilities you can contact me and I can turn the servers back on for you. Alternatively you can take a look at the <a href="{% url 'G865:final-video' %}">demonstration video</a> to see how it functioned.
    </div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="Submit" value="Add Task" class='site-button'>
    </form>
{% endblock %}

templates/G865/final-video.html
{% extends "G865/lesson-template.html" %}
{% load static %}

{% block title %}Geal's GEOG:865 Final Project Video Overview{% endblock %}
{% block page-title %}GEOG: 865 Final Project Video Overview{% endblock %}


{% block lesson-content %}
<div id="Disclaimer" style="color: red; background: black">
    The distributed EC2 instances used for this project have been shut down to save on running costs. If you would like to demo the capabilities you can contact me and I can turn the servers back on for you. Alternatively you can watch this video to see how it functioned.
</div>
    <video width="90%" style="margin-left: auto; margin-right: auto; display: block" controls>
        <source src="{% static 'G865/final_video.mp4' %}" type="video/mp4">
        Whoops... It looks like your browser doesn't support HTML5 and/or MP4 video files...
    </video>
{% endblock %}

templates/G865/index.html
{% extends "G865/lesson-template.html" %}
{% load static %}

{% block title %}Geal's GEOG:865 Lesson 4 Project{% endblock %}
{% block page-title %}GEOG: 865 Lesson 4 Project - Anywhere, USA Web App{% endblock %}

{% block head-ext %}
  <link rel="stylesheet" type="text/css" href="{% static 'G865/map.css' %}" />
  <link
      rel="stylesheet"
      href="https://js.arcgis.com/4.21/esri/themes/dark/main.css"
  />
  <script src="https://js.arcgis.com/4.21/"></script>
  <script src="{% static 'G865/lesson4.js' %}"></script>
{% endblock %}

{% block lesson-content %}
    <div id="Disclaimer" style="color: red; background: black">
      The server that ran this application has been shut down since the ArcGIS server license used during the class expired. This page is kept purely for historical purposes. You can see what this application used to look like by taking a look at the application <a href="{% url 'G865:lesson-4-video' %}">demonstration video</a>
    </div>
    <div id="viewDiv"></div>
{% endblock %}

templates/G865/l4-video copy.html
{% extends "G865/lesson-template.html" %}
{% load static %}

{% block title %}Geal's GEOG:865 Lesson 4{% endblock %}
{% block page-title %}GEOG: 865 Lesson4 - Video Web App Walkrough{%endblock %}


{% block lesson-content %}
    <video width="90%" style="margin: 20px; margin-left: auto; margin-right: auto; display: block" controls>
        <source src="{% static 'G865/l4-video.mp4' %}" type="video/mp4">
        Whoops... It looks like your browser doesn't support HTML5 and/or MP4 video files...
    </video>

{% endblock %}

templates/G865/l4-video.html
{% extends "G865/lesson-template.html" %}
{% load static %}

{% block title %}Geal's GEOG:865 Lesson 4{% endblock %}
{% block page-title %}GEOG: 865 Lesson4 - Video Web App Walkrough{%endblock %}


{% block lesson-content %}
    <video width="90%" style="margin: 20px; margin-left: auto; margin-right: auto; display: block" controls>
        <source src="{% static 'G865/l4-video.mp4' %}" type="video/mp4">
        Whoops... It looks like your browser doesn't support HTML5 and/or MP4 video files...
    </video>

{% endblock %}

templates/G865/lesson-template.html
{% extends "G865/template.html" %}

{% block title %}Geal's GEOG:865 Lesson Content {% endblock %}

{% block flex-content %}
    <div class="bubble-container" id="lesson-bubble">
        {% block lesson-content %}Whoops... It looks like the content for this lesson hasn't been uploaded yet.{% endblock %}
    </div>
{% endblock%}

templates/G865/lesson5.html
{% extends "G865/lesson-template.html" %}
{% load static %}

{% block title %}Geal's GEOG:865 MapBox Application{% endblock %}
{% block page-title %}GEOG: 865 Lesson5 - MapBox Application{%endblock %}

{% block head-ext %}
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.js"></script>
    <script src="{% static 'G865/lesson5.js' %}"></script>
    <style>
        #map {
            padding: 0;
            margin: 0;
            height: 80vh;
            width: 90%;
            margin-left: auto;
            margin-right: auto;
            position: relative;
            z-index: 0;
          }
    </style>
{%endblock%}


{% block lesson-content %}

<h1 id="title">Rapid City Addresses/Bandwidth Availability</h1>
<div id="map"></div>

{% endblock %}

templates/G865/queue-submit.html
{% extends "G865/lesson-template.html" %}
{% load static %}

{% block title %}Geal's GEOG:865 Queue Submitter{% endblock %}
{% block page-title %}Queue Task Submitted Successfully!{%endblock %}


{% block lesson-content %}
    <p>
        Your queue task "{{task_name}}" has been submitted succesfully.
        It has been assigned task ID #
        <a href="{% url 'G865:task-item' task_id='{{group_id}}' %}">{{group_id}}</a>.
    </p>
    <ul>
        <li> <a href="{% url 'G865:task-list' %}">View my submitted tasks</a></li>
        <li> <a href="">Add another task to queue</a></li>
    </ul>
{% endblock %}

templates/G865/task-item.html
{% extends "G865/lesson-template.html" %}
{% load static %}

{% block title %}Geal's GEOG:865 EC2 Server Manager{% endblock %}
{% block page-title %}GEOG: 865 EC2 Server Manager{%endblock %}


{% block lesson-content %}
    <p><a href="{% url 'G865:task-list' %}">Go to my task list</a></p>
    <h2>{{item.name}} Task Details</h2>
    <ul>
        <li>ID: {{item.id}}</li>
        <li>Creator: {{item.creator_user.username}}</li>
        <li>Uploaded File: {{item.upload_file_name}}</li>
        <li>Buffers: {{item.buffer_string}}</li>
        <li>Time Started: {{item.start_time}}</li>
        <li>{{completed_features}} / {% widthratio item.number_features 1 item.number_buffers %}
            ({{item.number_features}} points X {{item.number_buffers}} buffers)
        </li>
        {% if item.output_file %}
            <li>Download Results</li>
        {% endif %}
    </ul>

{% endblock %}

templates/G865/task-list.html
{% extends "G865/lesson-template.html" %}
{% load static %}

{% block title %}Geal's GEOG:865 EC2 Server Manager{% endblock %}
{% block page-title %}GEOG: 865 EC2 Server Manager{%endblock %}


{% block lesson-content %}
    <h2>Queue Tasks Submitted By {{user.username}}</h2>
    <ul>
        {% for task in tasks %}
        <li>
            <a href="{% url 'G865:task-item' task_id=task.id %}">
            Task #{{task.id}}
        </a></li>
        <ul>
            <li>Name: {{task.name}}</li>
            <li>Uploaded File: {{task.upload_file_name}}</li>
            <li>Buffers: {{task.buffer_string}}</li>
            <li>{{completed_features}} / {% widthratio task.number_features 1 task.number_buffers %}
                ({{task.number_features}} points X {{task.number_buffers}} buffers)
            </li>
            {% if task.output_file %}
                <li><a href="{{task.output_file.url}}">Download Results</a></li>
            {% endif %}
        </ul>
        {% endfor %}
    </ul>


{% endblock %}

templates/G865/template.html
{% extends "main/template.html" %}
{% load static %}

{% block head-ext %}{% endblock %}
{% block title %}Geal's GEOG: 865 E-Portfolio{% endblock %}

{% block page-title %}Welcome to Geal's GEOG: 865 E-Portfolio!{% endblock %}

{% block navbar %}
<div id="local-navbar">
    <a href="{% url 'G865:G865' %}" class="local-nav-button bubble-container">865 Web App</a>
    <a href="{% url 'G865:lesson-4-video' %}" class="local-nav-button bubble-container">Web App Video</a>
    <div class="local-nav-dropdown">
        <div class="local-nav-button bubble-container">Final Project &#9660</div>
        <div class="dropdown-content">
            <a href=" {% url 'G865:final-queue' %}" class="local-nav-dropdown-item">Queue Task Submitter</a>
            <a href=" {% url 'G865:final-ec2' %}" class="local-nav-dropdown-item">EC2 Instance Manager</a>
            <a href=" {% url 'G865:task-list' %}" class="local-nav-dropdown-item">Task List</a>
            <a href="{% url 'G865:final-video' %}" class="local-nav-dropdown-item">Video Overview</a>
            <a href="url 'G865:final-client' %}" class="local-nav-dropdown-item">Client Processor</a>
        </div>
    </div>
</div>
{% endblock %}

{% block  flex-content %}{% endblock %}

templates/G865/test.html
{% extends "G865/lesson-template.html" %}
{% load static %}

{% block title %}Geal's GEOG:865 MapBox Leaflet Test{% endblock %}
{% block page-title %}GEOG: 865 Lesson5 - MapBox Leaflet Test{%endblock %}

{% block head-ext %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.css" type="text/css" crossorigin="">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.js" crossorigin=""></script>
    <script src="{% static 'G865/test.js' %}"></script>
    <style>
    #mapid {
        width: 512px;
        height: 512px;
        border: 1px solid #ccc;
    }

    .leaflet-container {
        background: #fff;
    }
    </style>
{%endblock%}


{% block lesson-content %}

<h1 id="title">Favorite restaurants</h1>
<div id="mapid" onload="init()"></div>

{% endblock %}